import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

type Section = {
  id: string;
  title: string;
  content: React.ReactNode;
};

const sections: Section[] = [
  {
    id: 'disclaimer',
    title: 'Disclaimer',
    content: (
      <div className="space-y-3 text-sm leading-relaxed" style={{ opacity: 0.7 }}>
        <p>
          <strong>This tool is provided for informational and educational purposes only.</strong> The
          infrastructure risk scores and assessments generated by this tool are heuristic estimates
          based on publicly available data signals, and <em>do not constitute definitive proof</em>{' '}
          of malicious intent, compromise, or safety.
        </p>
        <p>
          Results should be used as one of many signals in a broader security investigation — not as
          a standalone verdict. Always validate findings through multiple independent sources before
          taking any enforcement, blocking, or legal action.
        </p>
        <p>
          The authors of this tool bear no responsibility for actions taken based on the output of
          this scanner.
        </p>
      </div>
    ),
  },
  {
    id: 'ethics',
    title: 'Ethical Use Policy',
    content: (
      <div className="space-y-3 text-sm leading-relaxed" style={{ opacity: 0.7 }}>
        <p>
          This tool is designed for <strong>legitimate security research, threat hunting, and
          infrastructure vetting</strong> by security professionals, IT administrators, and students
          learning about cybersecurity.
        </p>
        <p>By using this tool, you agree that you will:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Only scan domains you own, or have explicit written permission to investigate.</li>
          <li>Not use the output to harass, threaten, or unjustly target domain owners.</li>
          <li>Not use this tool to facilitate any form of cyber attack, fraud, or unauthorized access.</li>
          <li>Comply with all applicable local, national, and international laws, including but not
            limited to the Computer Fraud and Abuse Act (CFAA), GDPR, and equivalent legislation
            in your jurisdiction.</li>
          <li>Treat third-party domain owners with respect and not publish unverified accusations
            based solely on this tool's output.</li>
        </ul>
        <p className="font-semibold" style={{ opacity: 1 }}>
          Misuse of this tool may constitute a criminal offense. If you are unsure whether your
          intended use is lawful, consult a qualified legal professional before proceeding.
        </p>
      </div>
    ),
  },
  {
    id: 'data',
    title: 'Data Sources & Privacy',
    content: (
      <div className="space-y-3 text-sm leading-relaxed" style={{ opacity: 0.7 }}>
        <p>This tool queries the following <strong>publicly available, passive data sources</strong>:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>WHOIS databases</strong> — Domain registration records, creation dates, and registrar information.</li>
          <li><strong>DNS resolvers</strong> — Public A, AAAA, MX, NS, and TXT records (including SPF and DMARC).</li>
          <li><strong>TLS certificate handshake</strong> — Certificate validity, issuer, and expiration. No data is transmitted beyond a standard TLS ClientHello.</li>
          <li><strong>HTTP response headers</strong> — Only security-relevant HTTP headers from a standard GET request are inspected. No cookies or body content are stored.</li>
        </ul>
        <p>
          <strong>No personal data is stored.</strong> Scans are stateless — we do not log, store, or
          share domain queries, IP addresses, or scan results. All processing occurs in-memory and is
          discarded after the response is sent.
        </p>
        <p>
          Third-party services (WHOIS registrars, DNS resolvers) may log queries independently
          according to their own privacy policies.
        </p>
      </div>
    ),
  },
  {
    id: 'limitations',
    title: 'Limitations & Accuracy',
    content: (
      <div className="space-y-3 text-sm leading-relaxed" style={{ opacity: 0.7 }}>
        <p>
          The trust score is a <strong>heuristic approximation</strong> and has the following known
          limitations:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            <strong>False positives:</strong> Legitimate newly registered domains (e.g., a startup
            that launched today) will receive low trust scores despite posing no threat.
          </li>
          <li>
            <strong>False negatives:</strong> Malicious infrastructure that mimics legitimate
            configurations (valid TLS, aged domain, correct SPF/DMARC) may receive high trust scores.
          </li>
          <li>
            <strong>WHOIS redaction:</strong> Many registrars now redact WHOIS data under GDPR.
            Unavailable WHOIS does not imply malicious intent.
          </li>
          <li>
            <strong>CDN / proxy layers:</strong> Sites behind Cloudflare or similar CDNs may not
            expose their true security headers or TLS configuration in responses.
          </li>
          <li>
            <strong>No behavioral analysis:</strong> This tool does not analyze page content,
            embedded scripts, redirect chains, or actual malicious payloads.
          </li>
        </ul>
        <p>
          For comprehensive threat intelligence, combine this tool with reputation feeds, sandboxing,
          and behavioral analysis platforms.
        </p>
      </div>
    ),
  },
  {
    id: 'tos',
    title: 'Terms of Service',
    content: (
      <div className="space-y-3 text-sm leading-relaxed" style={{ opacity: 0.7 }}>
        <p>
          By using the Threat Intelligence Scraper ("the Service"), you agree to the following terms:
        </p>
        <ol className="list-decimal pl-5 space-y-2">
          <li>
            <strong>Acceptable Use.</strong> You may only use the Service for lawful purposes. You
            may not use the Service to conduct unauthorized reconnaissance, facilitate attacks, or
            violate any individual's or organization's rights.
          </li>
          <li>
            <strong>No Warranty.</strong> The Service is provided "as-is" without warranties of any
            kind, express or implied. We make no guarantees regarding accuracy, availability, or
            fitness for any particular purpose.
          </li>
          <li>
            <strong>Limitation of Liability.</strong> To the maximum extent permitted by applicable
            law, the authors and contributors of this Service shall not be liable for any direct,
            indirect, incidental, consequential, or punitive damages arising from your use of or
            reliance on the Service.
          </li>
          <li>
            <strong>Rate Limiting & Fair Use.</strong> Automated, bulk, or abusive querying of the
            Service is prohibited. Excessive usage that degrades service for other users may result
            in access termination.
          </li>
          <li>
            <strong>Modifications.</strong> These terms may be updated at any time. Continued use of
            the Service constitutes acceptance of the revised terms.
          </li>
          <li>
            <strong>Governing Law.</strong> These terms shall be governed by the laws of the
            applicable jurisdiction of the Service operator.
          </li>
        </ol>
      </div>
    ),
  },
  {
    id: 'responsible',
    title: 'Responsible Disclosure',
    content: (
      <div className="space-y-3 text-sm leading-relaxed" style={{ opacity: 0.7 }}>
        <p>
          If you discover a security vulnerability in this tool or its infrastructure, we strongly
          encourage you to follow responsible disclosure practices:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Do not publicly disclose the vulnerability before a fix has been developed and deployed.</li>
          <li>Do not exploit the vulnerability beyond what is necessary to demonstrate its existence.</li>
          <li>Report findings privately to the project maintainer with sufficient detail to reproduce
            the issue.</li>
          <li>Allow a reasonable timeframe (90 days is the industry standard) for remediation before
            publishing your research.</li>
        </ul>
        <p>
          We are committed to addressing security vulnerabilities promptly and will credit
          researchers who follow responsible disclosure in our changelog.
        </p>
      </div>
    ),
  },
];

const AccordionItem = ({ section, index }: { section: Section; index: number }) => {
  const [open, setOpen] = useState(false);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-60px' }}
      transition={{ duration: 0.5, delay: index * 0.05, ease: [0.16, 1, 0.3, 1] }}
      className="border-b"
      style={{ borderColor: 'color-mix(in srgb, var(--foreground) 10%, transparent)' }}
    >
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between py-5 text-left group"
      >
        <span className="font-bold uppercase tracking-widest text-sm group-hover:opacity-60 transition-opacity">
          {section.title}
        </span>
        <motion.span
          animate={{ rotate: open ? 45 : 0 }}
          transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
          className="text-xl leading-none"
          style={{ opacity: 0.4 }}
        >
          +
        </motion.span>
      </button>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="content"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
            style={{ overflow: 'hidden' }}
          >
            <div className="pb-6">{section.content}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export const Footer = () => {
  return (
    <footer
      className="w-full border-t"
      style={{ borderColor: 'color-mix(in srgb, var(--foreground) 10%, transparent)' }}
    >
      {/* Marquee banner */}
      <div
        className="overflow-hidden py-4 border-b"
        style={{
          borderColor: 'color-mix(in srgb, var(--foreground) 10%, transparent)',
          backgroundColor: 'color-mix(in srgb, var(--foreground) 4%, transparent)',
        }}
      >
        <motion.div
          animate={{ x: ['0%', '-50%'] }}
          transition={{ duration: 20, repeat: Infinity, ease: 'linear' }}
          className="flex gap-12 whitespace-nowrap"
        >
          {Array.from({ length: 8 }).map((_, i) => (
            <span
              key={i}
              className="text-xs font-bold uppercase tracking-widest"
              style={{ opacity: 0.3 }}
            >
              Threat Intel Scraper &nbsp;·&nbsp; For Security Research Only &nbsp;·&nbsp; Use Responsibly &nbsp;·&nbsp; No Data Stored &nbsp;·&nbsp;
            </span>
          ))}
        </motion.div>
      </div>

      {/* Legal sections */}
      <div className="max-w-3xl mx-auto px-6 py-16">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          className="mb-10 space-y-2"
        >
          <p className="text-xs uppercase tracking-widest font-bold" style={{ opacity: 0.3 }}>
            Legal & Ethics
          </p>
          <h2 className="text-3xl font-black uppercase tracking-tighter">
            Terms, Ethics
            <br />
            <span style={{ opacity: 0.3 }}>&amp; Responsible Use</span>
          </h2>
          <p className="text-sm max-w-lg" style={{ opacity: 0.5 }}>
            This tool performs passive, read-only analysis of publicly available infrastructure data.
            Read below to understand its limitations and your responsibilities as a user.
          </p>
        </motion.div>

        <div>
          {sections.map((section, i) => (
            <AccordionItem key={section.id} section={section} index={i} />
          ))}
        </div>

        {/* Bottom bar */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, delay: 0.3 }}
          className="mt-16 pt-8 border-t flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
          style={{ borderColor: 'color-mix(in srgb, var(--foreground) 10%, transparent)' }}
        >
          <div className="space-y-1">
            <p className="font-black uppercase tracking-widest text-sm">Threat Intel Scraper</p>
            <p className="text-xs" style={{ opacity: 0.35 }}>
              Open-source OSINT tool for cybersecurity professionals.
            </p>
            <p className="text-xs font-semibold" style={{ opacity: 0.55 }}>
              by Ajey Pandey
            </p>
          </div>
          <div className="text-xs space-y-1 text-right" style={{ opacity: 0.35 }}>
            <p>For educational &amp; authorized security use only.</p>
            <p>Not a substitute for professional security assessment.</p>
          </div>
        </motion.div>
      </div>
    </footer>
  );
};
